### ISSUE TITLE
Initial node setup

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/upload-service#1]
We need to the initial repository setup:

1. editorconfig + initial readme + initial package.json
2. eslint
3. babel 
4. jest
5. travis

Side note: I recommend tabs [for accessibility reasons](https://twitter.com/sarah_federman/status/1146544481556033537?lang=en) but I believe that spaces are preferred at an org level, so we'll go with spaces!

**Comment by slifty** [comment]
Decided to just stick with npm instead of yarn -- I personally enjoy some of the little things about yarn, but not enough to suggest requiring an additional dependency!  Yarn used to be better, now they're a bit closer to feature parity.

**Comment by jasonaowen** [comment]
> Side note: I recommend tabs [for accessibility reasons](https://twitter.com/sarah_federman/status/1146544481556033537?lang=en) but I believe that spaces are preferred at an org level, so we'll go with spaces!

This is a pretty compelling argument! We're setting some new patterns with this codebase, and although I haven't worked on a codebase that prefers tabs before, I'd be willing to try it here. At worst, we can do an automated reformat later, which just about every codebase I've ever worked on has had at least once in its commit history anyway.
