### ISSUE TITLE
Figure out deployment strategy

### ISSUE THREAD

**Issue by jasonaowen** [PermanentOrg/upload-service#13]
How will we deploy this service?

## Options

There are three main options we've considered:

1. deploy onto a standalone micro EC2 instance
2. deploy alongside the rest of the application
3. deploy via [docker on AWS](https://aws.amazon.com/docker/)

Are there other options we should look at?

## Environments

We currently have three environments: dev, staging, and prod. Developers also have a [local instance, manged by vagrant](https://github.com/PermanentOrg/devenv/). Our solution will need to be automatically deployed in the three hosted environments, and we'll need to write out instructions on how to make it work with local.

How do we want changes to flow between dev, staging, and prod? Any breaking changes would need to be coordinated with the PHP API which calls this.

**Comment by xmunoz** [comment]
My opinion is that the new uploader should be deployed directly on a small EC2 instance without Docker. The Amazon container offering (ECS) looks complicated to stand up, and given the lack of operational capacity at Permanent, this deployment configuration could quickly become unmaintainable.

**Comment by xmunoz** [comment]
Another reason to simply deploy it on the same box is that this would make the local development environment configuration conform to the prod config. If we do anything else, running the new uploader on the local dev environment, which is a hard requirement of this work, becomes more complex.
