### ISSUE TITLE
Change CI from travis to github actions

### ISSUE THREAD

**Issue by xmunoz** [PermanentOrg/upload-service#18]
Add a github action to run tests on PRs.

**Comment by xmunoz** [comment]
We are already using travis

**Comment by slifty** [comment]
We talked a bit about this in a slack DM -- @xmunoz made the legit point that using travis requires us to manage an entire additional set of permissions (and environment variables are a bit harder to enter) and is suggesting we move to github actions.

I'm fine with that personally, just checking if anybody else has a strong opinion!

**Comment by xmunoz** [comment]
Travis has separate permissions that need to managed. I think we should default to Github's CI solution so that org members can easily manage repo secrets and permissions.

**Comment by jasonaowen** [comment]
I disabled Travis on this repo:

![Screenshot of Travis CI configuration page](https://user-images.githubusercontent.com/1494855/98594459-89a3a800-2289-11eb-958e-b11421f4703b.png)

It's puzzling to me that you were faced with that permissions problem, but I'm glad you were able to get past it!
