### ISSUE TITLE
Add actual build step to Action

### ISSUE THREAD

**Issue by andrewatwood** [PermanentOrg/upload-service#29]
The current GitHub action does a lot of things but doesn't actually build and compile the service down to plain JavaScript, so the resulting `tar` that gets deployed is just the source code and dependencies

**Comment by andrewatwood** [comment]
So it turns out that the `npm start` command actually runs the project with `babel-node`, straight from the TypeScript without needing compilation:
```
babel-node --extensions \".ts,.tsx\" src/index.ts
```

Which explains where the initial error was about `babel` and not missing something from `/lib`.

But `babel`-related packages are marked as dev dependencies and thus not installed when the `--production` flag is set on `npm install` as per the build script here. It works in the `devenv` environment because the unflagged `npm install` is run, so babel is present and the service can run

**Comment by jasonaowen** [comment]
Thanks for working on this! I think you described the problem well.

However, let's not plan to run `babel-node` in production. It's good for developing, but the [docs](https://babeljs.io/docs/en/babel-node) say:

> You should not be using `babel-node` in production. It is unnecessarily heavy, with high memory usage due to the cache being stored in memory. You will also always experience a startup performance penalty as the entire app needs to be compiled on the fly.

I think the original solution you described is correct: we need to build the project in an environment with the dev dependencies installed, and then we need to deploy that built project into an environment with only the production dependencies installed.
