### ISSUE TITLE
Integrate with Sentry

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/upload-service#3]
#### Description

We want to build this service in a way that integrates with monitoring out of the box, so lets add support for Sentry.

#### Relevant Resources / Research

- [Sentry node documentation](https://docs.sentry.io/platforms/node/)

**Comment by xmunoz** [comment]
I've invite @jasonaowen and you to our Sentry org. From there, you should be able to create a new project and get a token.

**Comment by jasonaowen** [comment]
I received the invitation and successfully joined the Sentry organization.

**Comment by xmunoz** [comment]
Open questions:
- Sample rate for sentry
- Sentry/typescript source maps

**Comment by slifty** [comment]
Oh right -- should have posted those questions here! ty for carrying it over.

**Comment by slifty** [comment]
Following up here: sample rate of 1 / default is legit.

Going to work with @andrewatwood on the source map question.

**Comment by xmunoz** [comment]
The upload-config repository requires two environment variables (SENTRY_ENVIRONMENT and SENTRY_DSN) in order to support Sentry. We need to update the service definition to provide those vars.

**Comment by xmunoz** [comment]
You can configure the `SENTRY_DSN` here: https://github.com/PermanentOrg/upload-service/settings/secrets/actions/new
The `SENTRY_ENVIRONMENT` can be configured in the deploy script: https://github.com/PermanentOrg/upload-service/blob/main/.github/workflows/deploy.yml

Once you add the `SENTRY_DSN` secret, reassign this issue. I can send the PR to update the build and deployment script.
