### ISSUE TITLE
S3 integration

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/upload-service#5]
#### Description
This service needs to coordinate with Amazon S3 to get an upload token to return to the client.

Lets implement that functionality.

#### Relevant Resources / Research

- https://devcenter.heroku.com/articles/s3#file-uploads
- https://devcenter.heroku.com/articles/s3-upload-node
- https://github.com/willwebberley/NodeDirectUploader

**Comment by slifty** [comment]
This is useful documentation that shows a few of the ways configuration can work: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

**Comment by xmunoz** [comment]
^ That is currently how all of our machines are configured. For your app, you can assume that the required environment variables exist.

**Comment by slifty** [comment]
This is now closed via #11 

Note that the AWS configuration will have to be explicit via environment variables, due to an AWS SDK bug.
