### ISSUE TITLE
Define the Uploader Service API

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/upload-service#7]
### Description
This uploader service is responsible for receiving upload initiation requests and responding to the requests with a message that specifies where the client should post the uploading file.

It is NOT responsible for providing information about an upload status.

We need to design and document the API that this service provides.

### Related Thoughts
We will need to decide if this service should respond with identifying information about the record that file will ultimately be associated with.  There was indication on the call that there might be a preference to NOT create a record until after the file has actually been received by S3.  If that is the case, record IDs would not be generated until after the S3 upload is completed and handled by the rest of the system.

**Comment by slifty** [comment]
I don't think we need to go too crazy with naming right now, If / when we talk about api gateways / public api endpoints names will become more important (and potentially more rooted in things like domain, or with versions, or who knows what may come!).

For now this is just an internal endpoint.

Given that, here are some proposed API routes for this thing:

- POST `/signedUploadRequest`
- DELETE `/signedUploadRequest` 

This borrows from REST, even if it isn't truly a RESTful endpoint (there's not really much state to represent).

The logic is that a given upload request can be created via POST, and deleted via DELETE.

Some reasons for the naming:

1. this avoids any reference to S3 in the API.
2. It's descriptive and accurate.
3. It also allows for future upload related endpoints that aren't rooted in a signed request workflow.

(I don't expect DELETE to be implemented in this iteration, but wanted to mention it.)

**Comment by jasonaowen** [comment]
I think we're broadly on the same page here!

+1 to making an S3-agnostic name; ideally we'd be able to swap out the implementation to generate, say, Backblaze B2 URLs and the rest of the application wouldn't notice or care.

> DELETE /api/signedUploadRequest

Can you say more about what this endpoint would do, and when it would be called? My understanding is that the signatures generated for S3 are valid for a certain period of time, but I don't see anything about revoking them; see also the [`getSignedUrl` method from aws-sdk](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property).

> POST /api/signedUploadRequest

Two pieces here: that this is a `POST` request, and that the method name is `signedUploadRequest`; I'm fine with both of those.

I can see arguments for both `POST` and `GET` (which the [Heroku docs use](https://devcenter.heroku.com/articles/s3-upload-node#setting-up-the-app-side-node-code)), so I'm neutral there.

I worry a little that `signedUploadRequest` might still be too AWS-centric; maybe `uploadTargetUrl` or so? It's a surprisingly hard-to-name thing! Like I said, though, I'm fine to go with the proposed name.

The only other bit we haven't talked about yet is what data we send as part of the API request. Most importantly, are we including metadata about the file-to-upload? It looks like `<input type="file">` provides several pieces of metadata, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#Getting_information_on_selected_files): filename, size, MIME type, and last modified; probably we at least want the filename. I could see including all the information, even if we don't use it, in an effort to future-proof the API, but not sure whether or not that's a good idea.

Secondarily, we need to think about auth, sooner or later. Our interim plan is to have the PHP API proxy through to this API, so all we need to do is verify that the request is coming from the PHP API. That should be relatively easy, as it means the PHP API will be taking care of user authentication; I think we could simply look for a single secret token shared between the PHP API and this API. I'd particularly like to get @xmunoz's thoughts on that, though!

**Comment by slifty** [comment]
## Naming

Will sleep on the naming question (I have some thoughts but wanna see if they shift at all overnight).

(`fileDestinationUrl` might be good, see below).

## Fields
Regarding the fields, lets be sure to differentiate between required fields and optional fields.

But also... let's think about what this service is doing right now, given the PHP middleware.  We may actually not require *any* file metadata for this particular service *at this stage of its iteration*.  Hear me out...

### Service Design

In thinking about the fields, I want to reflect on the current iteration of the service design.

It might be appropriate to think of this as decoupled from the user upload workflow.  It's become something more atomic (and in the long term I could see the name of this service collapsing to something else that reflects the refined purpose).

What I mean is that this service exists, at this point, simply to generate file destination URLs (with a signed request, though to your point in the naming that could go away).  That destination URL could then be used for a variety of workflows.

Given this model, the the API shouldn't care WHY the URL is being generated, and shouldn't care about the Permanent context of that URL (i.e. eventual archive IDs).  It just needs to know enough to (A) validate that the url generation is allowed for the principal and then (B) take the steps necessary to generate that URL.

We'll have a middleware service (which PHP is functioning as) would be what connects that URL to the upload flow.

I bring this up here because this means that we would NOT need to have this endpoint require things like `permanent archive / destination ID`.

When we move away from PHP is when we'll decide if this `fileDestinationUrl` (hey maybe that should be the name) microservice stays micro, or if it ends up turning into something more explicitly coupled with the upload flow.

I just wanted to type all of that out.

(Side note: the truly-micro-microservice approach also might have more direct FOSS value outside of permanent, since others could set up the service in their own non-permanent projects in order to generate file destination URLs)

### So the fields

So at the very least I think we're going to want to know information about the principal who ultimately triggered the call.  For now this will just be used for logging, but eventually it would be used for verifying the authenticity / authorization of the request.

Depending on how this service evolves, we may want file metadata as well.  It's just for now the PHP is going to be handling all of that, and this service really is just generating a URL that the PHP is going to contextualize with a given upload.

So, for the *upload use case* (aka at the PHP level) I think that the more metadata we allow the client to pass the better, but the only fields that should be _required_ are those needed to actually process an upload.

Name, size, feel like must haves (name for the use case; size for integrity checks and prior-to-upload-verification that an upload is allowed for a given user).

Type is important, but I suspect we will not want to rely on client reported types for our internal systems / we may want to detect type as part of the upload process.

Other metadata feels useful to allow as optional fields which our system may or may not actually utilize.

It's not clear to me that this service needs any of that *yet*.

When we get rid of PHP, we may decide to change this service to be upload specific (at which point I think we would want to add those fields to this API) but we may also decide to create a *new* service that is upload specific, and which calls this service to generate a URL in the exact same way PHP will.

**Comment by jasonaowen** [comment]
> (`fileDestinationUrl` might be good, see below).

Yeah, I like that!

> Regarding the fields, lets be sure to differentiate between required fields and optional fields.

+1

> But also... let's think about what this service is doing right now, given the PHP middleware. We may actually not require _any_ file metadata for this particular service _at this stage of its iteration_. Hear me out...

That's a reasonable stance; if we're naming files after UUIDs or whatever and the only user-supplied data retained is the content of the uploaded file, that'd be fine.

> In thinking about the fields, I want to reflect on the current iteration of the service design.
> 
> It might be appropriate to think of this as decoupled from the user upload workflow. It's become something more atomic.
> 
> What I mean is that this service exists, at this point, simply to generate file destination URLs (with a signed request, though to your point in the naming that could go away). That destination URL could then be used for a variety of workflows.
> 
> Given this model, the the API shouldn't care WHY the URL is being generated, and shouldn't care about the Permanent context of that URL (i.e. eventual archive IDs). It just needs to know enough to (A) validate that the url generation is allowed for the principal and then (B) take the steps necessary to generate that URL.

+1 to all of that, and in particular I completely agree about keeping Permanent context out. 

What I meant to be asking was: are we going to use any of the file metadata in generating the destination URL? Like if I say "I want to upload `my-great-photo.jpg`", is the resulting destination URL going to have the string `my-great-photo` in it? If not, if we returned a URL like `https://permanent-uploads.s3.us-west-2.amazonaws.com/0d753555-dafa-4f43-9aaf-b8076cb7e807`, then we wouldn't need to pass any file metadata in.

I believe the current behavior does not encode the user-supplied filename in the object stored in S3, so I think I'm talking myself around to not passing in filename or any other metadata to this endpoint.

> (Side note: the truly-micro-microservice approach also might have more direct FOSS value outside of permanent, since others could set up the service in their own non-permanent projects in order to generate file destination URLs)

+1

>> Secondarily, we need to think about auth, sooner or later. Our interim plan is to have the PHP API proxy through to this API, so all we need to do is verify that the request is coming from the PHP API. That should be relatively easy, as it means the PHP API will be taking care of user authentication; I think we could simply look for a single secret token shared between the PHP API and this API.
>
> So at the very least I think we're going to want to know information about the principal that the call is ultimately associated with. For now this will just be used for logging, but eventually it would be used for verifying the authenticity / authorization of the request.

I can't tell if we're agreeing or not. :smile: I don't think we need this service to know anything about the user at this stage; I think the only authentication we need is to verify that the request came from the PHP API, like ssh host-based authentication. The authorization is simply "yes, if authenticated". I believe we intend to make this more complicated later, but for now we can keep it simple!

That may be what you meant by "principal" here, though, so sorry if I'm just restating what you wrote!

> Now, for the _upload use case_ (aka at the PHP level for now) I think that the more metadata we allow the client to pass the better, but the only fields that should be _required_ are those needed to actually process an upload.

+1

> Agreed that [the delete method] would likely be a noop at this point. In an abstract sense (ignoring S3 limitations) I think it's legitimate to be able to invalidate a given destination URL, but right, since it's not supported by S3...
> 
> Happy to remove this from the discussion!

+1

**Comment by slifty** [comment]
> I don't think we need this service to know anything about the user at this stage;

Agreed, (though your uncertainty about whether we agreed makes total sense: I was definitely suggesting we accept information about the "principal" which is more than what we need right now and possibly ever.)

**Comment by slifty** [comment]
Continuing your question around fields here, some proposed parameters:

1) "bucket" for the bucket path so the caller can specify which bucket to use.
2) "baseName" (optional) -- if not provided, a random file name would be generated.
3) "extention" (optional) -- if not provided, the file will not be provided an extension.

We could have the service configured with a default bucket (and make bucket optional) but we do use different buckets for different environments and I think making this a parameter decouples this service from the particular workflow it is being invoked for (for instance, we may want thumbnails to live in their own buckets at some point).

**Comment by slifty** [comment]
It looks like S3 does require the `ContentType` to be populated to generate a signed request.

Furthermore, we should allow the caller to specify the path within the bucket (not just thefilename).

So, with those two, we'd add:

3. `fileType` (required)
4. `path` (optional)
