### ISSUE TITLE
Set up a web framework

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/upload-service#8]
#### Description
We need to set up a web framework to create whatever endpoint(s) come from #7.

I see two choices:

1. [Express](https://www.npmjs.com/package/express) is ubiquitous.
2. [Fastify](https://www.npmjs.com/package/fastify) has better benchmarks and seems to be actively used.

#### Relevant Resources / Research
- https://medium.com/sharenowtech/there-are-expressjs-alternatives-590d14c58c1c

**Comment by slifty** [comment]
Some considerations:

I suspect that performance won't be a limiting factor for this service at the scale we're going to operate in the near future.

* Both seem similarly simple to use and set up.
* Both are actively developed.
* Express has 100x more downloads (14m vs 161k).

**Comment by jasonaowen** [comment]
I agree that performance is not the most important criteria for us.

This decision is very much linked to the outcome of https://github.com/PermanentOrg/meta/issues/1 , and I think cannot be made until we've decided on an approach there.

**Comment by slifty** [comment]
In our discussions about longer term architecture vision we did land on the idea that for the immediate term, this service will be accessed via HTTP, called from the PHP monolith.

Given that, I'd like to move forward and I think Express is the way to go!

**Comment by slifty** [comment]
Insofar as this issue might prompt some skeleton code structure, I like the structure outlined in [this post](https://www.coreycleary.me/project-structure-for-an-express-rest-api-when-there-is-no-standard-way/).
